### ISSUE TITLE
Feature Request: Ban multiple configs for the same interceptor.

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#148] opened 2020-09-08 07:14 UTC
Currently it is possible to send multiple different configs for the same `Interceptor` when calling `ServeMux.Handle`. This should be banned. Instead the method should probably panic if this occurs.

**Comment by empijei** [comment] 2021-05-31 09:44
Duplicate of #302

**Closed by empijei** 2021-05-31 09:44 UTC
Labels: core, enhancement, good first issue, v0.1
