### ISSUE TITLE
Clear headers map in safehttp.ResponseWriter.WriteError

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#189] opened 2020-10-05 14:56 UTC
In order to prevent leaks when an error occurs, we need to ensure the headers map is cleared before calling `http.Error` in the `safehttp.ResponseWriter.WriteError` funciton.

**Comment by kele** [comment] 2020-10-05 15:05
Why?

**Comment by maramihali** [comment] 2020-10-05 15:15
Currently, if some interceptor or handler sets a `SecretHeader` and then an error occurs, the `SecretHeader` will still still be sent. We want to prevent this, don't we?

**Comment by kele** [comment] 2020-10-08 07:06
Could you come up with a compelling example on why we'd want that? Also, it is quite important here to distinguish when the header is set (e.g. if you set your header in `Before()`, is it really that secret?).

**Comment by kele** [comment] 2020-10-08 07:11
This is actually a duplicate of #102.

**Closed by kele** 2020-10-08 07:11 UTC
Labels: enhancement, needs information, proposal
